### ISSUE TITLE
Rare crash in Panel

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1364]
This Panel crash is rare (I've encountered it only 3 times in months) but happened again -- a few minutes ago -- when I removed `copyq` by right clicking its icon in the status notifier and clicking Exit. The issue is not new and the backtrace is always as follows (apparently, `QMenu::popup()` is called for a nonexistent menu and has caused the crash.):
```
#0  0x00007f7766ec2f74 in QMenu::popup(QPoint const&, QAction*) () at /usr/lib/libQt5Widgets.so.5
#1  0x000055b6c70abb74 in  ()
#2  0x00007f7766d80a08 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#3  0x00007f7766f1b495 in QToolButton::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#4  0x00007f7766d40f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007f7766d48f81 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#6  0x00007f7765e1f060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#7  0x00007f7766d47f0a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007f7766d9bd81 in  () at /usr/lib/libQt5Widgets.so.5
#9  0x00007f7766d9e4c1 in  () at /usr/lib/libQt5Widgets.so.5
#10 0x00007f7766d40f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#11 0x00007f7766d48a06 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007f7765e1f060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#13 0x00007f776637e3d4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/libQt5Gui.so.5
#14 0x00007f776637ff36 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#15 0x00007f776635748c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Gui.so.5
#16 0x00007f775d62e4b1 in  () at /usr/lib/libQt5XcbQpa.so.5
#17 0x00007f7768b9c270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#18 0x00007f7768b9df69 in  () at /usr/lib/libglib-2.0.so.0
#19 0x00007f7768b9dfae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#20 0x00007f7765e79cd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#21 0x00007f7765e1d48b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#22 0x00007f7765e264d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#23 0x000055b6c703c576 in  ()
#24 0x00007f7765471f6a in __libc_start_main () at /usr/lib/libc.so.6
#25 0x000055b6c703cc3a in _start ()
```

**Comment by tsujan** [comment]
Too old and hasn't happened for a long time.
