### ISSUE TITLE
lxqt-panel: crash after trying to eject an ejected/unmounted volume with Removable Media

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt#1527]
As the title says -- it was a week ago and I'm not sure what happened. However:
```
#0  0x00007f55e478b364 in Solid::StorageAccess::isAccessible() const () at /usr/lib/libKF5Solid.so.5
#1  0x00007f55e4a8de9f in  () at /usr/lib/lxqt-panel/libmount.so
#2  0x00007f55fc34ec50 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#3  0x00007f55fd388513 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#4  0x00007f55fd38872c in  () at /usr/lib/libQt5Widgets.so.5
#5  0x00007f55fd389b22 in  () at /usr/lib/libQt5Widgets.so.5
#6  0x00007f55fd389cf6 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#7  0x00007f55fd47927b in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#8  0x00007f55fd2dd2b8 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007f55fd479324 in QToolButton::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#10 0x00007f55fd29da74 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#11 0x00007f55fd2a558a in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007f55fc324cb9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#13 0x00007f55fd2a4871 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007f55fd2f89b7 in  () at /usr/lib/libQt5Widgets.so.5
#15 0x00007f55fd2fb235 in  () at /usr/lib/libQt5Widgets.so.5
#16 0x00007f55fd29da74 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007f55fd2a5341 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007f55fc324cb9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007f55fc8cae34 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/libQt5Gui.so.5
#20 0x00007f55fc8ccdf6 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#21 0x00007f55fc8a6b7c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Gui.so.5
#22 0x00007f55f42d372d in  () at /usr/lib/libQt5XcbQpa.so.5
#23 0x00007f55fc32394c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#24 0x00007f55fc32bc46 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#25 0x0000560ad2a1f8a6 in  ()
#26 0x00007f55fb99106b in __libc_start_main () at /usr/lib/libc.so.6
#27 0x0000560ad2a1ffba in _start ()
```
LXQt is the latest git here.

**Comment by johndoe71rus** [comment]
Excuse me, can I suggest? Hide the applet icon if the devices are not connected.
