### ISSUE TITLE
XScreenSaver causes lxqt-session to dump core

### ISSUE THREAD

**Issue by kmiernik** [lxqt/lxqt#1803]
I have problem with lxqt and xscreensaver. Basically, closing the lid before xscreensaver locks the screen causes lxqt-session to dump core.

##### Expected Behavior

Obviously this should not happen, the work should be resumed normally.

##### Steps to Reproduce (for bugs)

1. Close laptop lid, screen is turned-off and locked
2. Wait for the xscreensaver specified lock time
3. Open the lid
4. After reopening lid the on-screen message from xscreensaver is
```
xscreensaver: 08:51:27: DPMSForceLevel(dpy, DPMSModeOff) did not change monitor state
xscreensaver: 08:51:27: not launching hack (throttled.)
xscreensaver: 08:51:27: LOCK Client  Message received while already locked
xscreensaver-command: window 0x00a00001 mapped
xscreensaver-command: suspending

xscreensaver-command: deactivating
```

The time is moment of lid closing
5. Upon unlocking xscreensaver the lxqt show message
```
Failed to run "xdg-screensaver lock".
Ensure you have a locker/screensaver compatible  with xdg-screensaver installed and running.
```
There is only OK option
6. lxqt-sesion dumps core (time is the moment of clicking OK button) and session is terminated
```
May 27 10:03:17 control systemd-coredump[29458]: Process 3625 (lxqt-session) of user xxx dumped core.
                                                 
                                                 Stack trace of thread 3625:
                                                 #0  0x00007fa8c2a72355 raise (libc.so.6 + 0x3c355)
                                                 #1  0x00007fa8c2a5b853 abort (libc.so.6 + 0x25853)
                                                 #2  0x00007fa8c2ab5878 __libc_message (libc.so.6 + 0x7f878)
                                                 #3  0x00007fa8c2abcd3a malloc_printerr (libc.so.6 + 0x86d3a)
                                                 #4  0x00007fa8c2abe370 _int_free (libc.so.6 + 0x88370)
                                                 #5  0x00007fa8c3d2b51a _ZN7QDialog4execEv (libQt5Widgets.so.5 + 0x35d51a)
                                                 #6  0x00007fa8c433047d n/a (liblxqt.so.0 + 0x4147d)
                                                 #7  0x00007fa8c4330615 n/a (liblxqt.so.0 + 0x41615)
                                                 #8  0x00007fa8c30b9d56 n/a (libQt5Core.so.5 + 0x2dfd56)
                                                 #9  0x00007fa8c2ff2539 _ZN8QProcess8finishedEiNS_10ExitStatusE (libQt5Core.so.5 + 0x218539)
                                                 #10 0x00007fa8c2ff7e86 n/a (libQt5Core.so.5 + 0x21de86)
                                                 #11 0x00007fa8c2ff7fbe n/a (libQt5Core.so.5 + 0x21dfbe)
                                                 #12 0x00007fa8c30b9d90 n/a (libQt5Core.so.5 + 0x2dfd90)
                                                 #13 0x00007fa8c30bd2e2 _ZN15QSocketNotifier9activatedEiNS_14QPrivateSignalE (libQt5Core.so.5 + 0x2e32e>
                                                 #14 0x00007fa8c30bd672 _ZN15QSocketNotifier5eventEP6QEvent (libQt5Core.so.5 + 0x2e3672)
                                                 #15 0x00007fa8c3b29652 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 +>
                                                 #16 0x00007fa8c30842d2 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2>
                                                 #17 0x00007fa8c30dbd06 n/a (libQt5Core.so.5 + 0x301d06)
                                                 #18 0x00007fa8c28a943c g_main_context_dispatch (libglib-2.0.so.0 + 0x5243c)
                                                 #19 0x00007fa8c28f6fa9 n/a (libglib-2.0.so.0 + 0x9ffa9)
                                                 #20 0x00007fa8c28a8221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                 #21 0x00007fa8c30db101 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFl>
                                                 #22 0x00007fa8c3082c0c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a8c>
                                                 #23 0x00007fa8c308b0a6 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2b10a6)

                                                 Stack trace of thread 29350:
                                                 #0  0x00007fa8c29e7e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                 #1  0x00007fa8b7800e1c n/a (i965_dri.so + 0x4f8e1c)
                                                 #2  0x00007fa8b7800a18 n/a (i965_dri.so + 0x4f8a18)
                                                 #3  0x00007fa8c29e1422 start_thread (libpthread.so.0 + 0x9422)
                                                 #4  0x00007fa8c2b35bf3 __clone (libc.so.6 + 0xffbf3)

                                                 Stack trace of thread 29351:
                                                 #0  0x00007fa8c29e7e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                 #1  0x00007fa8b7800e1c n/a (i965_dri.so + 0x4f8e1c)
                                                 #2  0x00007fa8b7800a18 n/a (i965_dri.so + 0x4f8a18)
                                                 #3  0x00007fa8c29e1422 start_thread (libpthread.so.0 + 0x9422)
                                                 #4  0x00007fa8c2b35bf3 __clone (libc.so.6 + 0xffbf3)

                                                 Stack trace of thread 3637:
                                                 #0  0x00007fa8c2b26b8f write (libc.so.6 + 0xf0b8f)
                                                 #1  0x00007fa8c28f0b4b n/a (libglib-2.0.so.0 + 0x99b4b)
                                                 #2  0x00007fa8bf52d8bd n/a (libQt5XcbQpa.so.5 + 0x5d8bd)
                                                 #3  0x00007fa8bf52d98d n/a (libQt5XcbQpa.so.5 + 0x5d98d)
                                                 #4  0x00007fa8c2ea4dcf n/a (libQt5Core.so.5 + 0xcadcf)
                                                 #5  0x00007fa8c29e1422 start_thread (libpthread.so.0 + 0x9422)
                                                 #6  0x00007fa8c2b35bf3 __clone (libc.so.6 + 0xffbf3)

                                                 Stack trace of thread 29349:
                                                 #0  0x00007fa8c29e7e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                 #1  0x00007fa8b7800e1c n/a (i965_dri.so + 0x4f8e1c)
                                                 #2  0x00007fa8b7800a18 n/a (i965_dri.so + 0x4f8a18)

                                                 Stack trace of thread 3638:
                                                 #0  0x00007fa8c2b2b05f __poll (libc.so.6 + 0xf505f)
                                                 #1  0x00007fa8c28f6f38 n/a (libglib-2.0.so.0 + 0x9ff38)
                                                 #2  0x00007fa8c28a8221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                 #3  0x00007fa8c30db101 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFl>
                                                 #4  0x00007fa8c3082c0c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a8c>
                                                 #5  0x00007fa8c2ea3c02 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc9c02)
                                                 #6  0x00007fa8c4077098 n/a (libQt5DBus.so.5 + 0x17098)
                                                 #7  0x00007fa8c2ea4dcf n/a (libQt5Core.so.5 + 0xcadcf)
                                                 #8  0x00007fa8c29e1422 start_thread (libpthread.so.0 + 0x9422)
                                                 #9  0x00007fa8c2b35bf3 __clone (libc.so.6 + 0xffbf3)

                                                 Stack trace of thread 29352:
                                                 #0  0x00007fa8c29e7e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                 #1  0x00007fa8b7800e1c n/a (i965_dri.so + 0x4f8e1c)
                                                 #2  0x00007fa8b7800a18 n/a (i965_dri.so + 0x4f8a18)
                                                 #3  0x00007fa8c29e1422 start_thread (libpthread.so.0 + 0x9422)
                                                 #4  0x00007fa8c2b35bf3 __clone (libc.so.6 + 0xffbf3)

                                                 #3  0x00007fa8c29e1422 start_thread (libpthread.so.0 + 0x9422)
                                                 #4  0x00007fa8c2b35bf3 __clone (libc.so.6 + 0xffbf3)

                                                 #24 0x0000563bf2ae23c8 n/a (lxqt-session + 0xb3c8)
                                                 #25 0x00007fa8c2a5d002 __libc_start_main (libc.so.6 + 0x27002)
                                                 #26 0x0000563bf2ae251e _start (lxqt-session + 0xb51e)
```

6. This is related to lxqt exclusively (e.g. lxde is not affected) to laptop/drivers (my other two computers running the same OS and software are not affected) and to xscreensaver 5.44. Downgrading xscreensaver to 5.43 and below makes everything work as it should.
7. The dpmsEnabled is False in .xscreensaver. I have tried to disable xscreesaver (mode: disable xscreensaver) and different modes of screensaver (including blank screen only, random scrensavers etc.) result is the same. Upon removing xscreensaver from autostart there is only the message from point 5 (Failed to run...) , but session is not terminated.

##### Context

This bug makes lxqt on this laptop unusable with the latest version of xscreensaver. Even if it is related to some changes in xscreensaver, the lxqt-session should not terminate with core dump.

##### System Information

* Distribution & Version: ArchLinux
* Kernel: 5.6.14-arch1-1
* Qt Version:  5.14.2-3
* liblxqt Version: 0.15.0-2
* Package version: 0.15.0-1

**Comment by tsujan** [comment]
Please attach a backtrace by using `coredumpctl gdb <PROGRAM_NAME>`, then `where` (paste what comes after `where`) and then press `q` to exit.

**Comment by tsujan** [comment]
The crash you see may be the same as in https://github.com/lxqt/lxqt/issues/1792, in which case, it's already fixed in https://github.com/lxqt/liblxqt/pull/253. That could be known if you attach a backtrace.

If it's the same crash, we could make a point release for liblxqt.

**Comment by kmiernik** [comment]
Here's a backtrace

```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `lxqt-session'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007faf958db355 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7faf929e5800 (LWP 8002))]
(gdb) where
#0  0x00007faf958db355 in raise () at /usr/lib/libc.so.6
#1  0x00007faf958c4853 in abort () at /usr/lib/libc.so.6
#2  0x00007faf9591e878 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007faf95925d3a in  () at /usr/lib/libc.so.6
#4  0x00007faf95927370 in _int_free () at /usr/lib/libc.so.6
#5  0x00007faf96b9451a in QDialog::exec() () at /usr/lib/libQt5Widgets.so.5
#6  0x00007faf9719947d in  () at /usr/lib/liblxqt.so.0
#7  0x00007faf97199615 in  () at /usr/lib/liblxqt.so.0
#8  0x00007faf95f22d56 in  () at /usr/lib/libQt5Core.so.5
#9  0x00007faf95e5b539 in QProcess::finished(int, QProcess::ExitStatus) ()
    at /usr/lib/libQt5Core.so.5
#10 0x00007faf95e60e86 in  () at /usr/lib/libQt5Core.so.5
#11 0x00007faf95e60fbe in  () at /usr/lib/libQt5Core.so.5
#12 0x00007faf95f22d90 in  () at /usr/lib/libQt5Core.so.5
#13 0x00007faf95f262e2 in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () at /usr/lib/libQt5Core.so.5                                       
#14 0x00007faf95f26672 in QSocketNotifier::event(QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#15 0x00007faf96992652 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /usr/lib/libQt5Widgets.so.5
#16 0x00007faf95eed2d2 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /usr/lib/libQt5Core.so.5
#17 0x00007faf95f44d06 in  () at /usr/lib/libQt5Core.so.5
#18 0x00007faf9571243c in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#19 0x00007faf9575ffa9 in  () at /usr/lib/libglib-2.0.so.0
#20 0x00007faf95711221 in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
#21 0x00007faf95f44101 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5                             
#22 0x00007faf95eebc0c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5                                                
#23 0x00007faf95ef40a6 in QCoreApplication::exec() ()
    at /usr/lib/libQt5Core.so.5
#24 0x0000559e6ddbe3c8 in  ()
#25 0x00007faf958c6002 in __libc_start_main () at /usr/lib/libc.so.6
#26 0x0000559e6ddbe51e in _start ()
```

Sorry if this was already fixed, somehow I missed that issue when searching for similar reports. The difference I see is that with xscreensaver not started I do not reproduce core dump.

**Comment by tsujan** [comment]
OK, it's the same as in https://github.com/lxqt/lxqt/issues/1792.

**Comment by tsujan** [comment]
> Sorry if this was already fixed, somehow I missed that issue when searching for similar reports.

It's OK. At first, I wasn't sure either that they were the same issue.

**Comment by tsujan** [comment]
@yan12125 @jubalh @luis-pereira 
Any objection to a point release for liblxqt?

**Comment by yan12125** [comment]
> Any objection to a point release for liblxqt?

I'm fine with a new release.

**Comment by jubalh** [comment]
Me too.

**Comment by luis-pereira** [comment]
> Any objection to a point release for liblxqt?

None.

**Comment by tsujan** [comment]
@jubalh, @yan12125, @Chiitoo
liblxqt 0.15.1 is released.

**Comment by yan12125** [comment]
Thanks! The new version is uploaded to Arch.

tsujan <notifications@github.com> 於 2020年5月29日 週五 下午5:09寫道：

**Comment by tsujan** [comment]
@kmiernik You could upgrade to liblxqt 0.15.1-1 to get rid of the issue.

**Comment by kmiernik** [comment]
Sorry, although now the lxsession does not crashes, but with xscreensaver enabled there is the "Failed to run xdg-screensaver lock" message. Just a small inconvenience but perhaps something to polish in the future. It looks like it is due double locking: first closing the lid locks the screen, and then it is locked again due to power management, and this one fails to lock already locked screen causing the error message.

**Comment by tsujan** [comment]
> first closing the lid locks the screen, and then it is locked again due to power management

The first one isn't done by LXQt? If so, you might need to disable it. It's a bug only if LXQt tries to lock screen twice. Does it?

It's a long time I haven't had xscreensaver.

**Comment by kmiernik** [comment]
I did some more checks. It looks like regardless of the xscreensaver enabled or not, it is the lxqt-powermanagement that is causing this message. This happens upon calling suspend, and it is happening either when action is lid closed or idle watch timer.
The xscreensaver log without screensaver blanking/locking is
```
screensaver: 09:25:11: starting de-race timer (10 seconds.)
xscreensaver: 09:25:11: awaiting idleness.
xscreensaver: 09:25:21: de-race completed.
xscreensaver: 09:32:00: SUSPEND ClientMessage received.
xscreensaver: 09:32:00: locking.
xscreensaver: 09:32:00: 0: locked mode switching.
xscreensaver: 09:32:00: DPMSForceLevel(dpy, DPMSModeOff) did not change monitor 
power state.
xscreensaver: 09:32:00: user is idle (ClientMessage)
xscreensaver: 09:32:00: blanking screen at Sat May 30 09:32:00 2020.
xscreensaver: 09:32:00: 0: grabbing keyboard on 0x1be... GrabSuccess.
xscreensaver: 09:32:00: 0: grabbing mouse on 0x1be... GrabSuccess.
xscreensaver: 09:32:00: not launching hack (throttled.)
xscreensaver: 09:32:00: LOCK ClientMessage received while already locked.
xscreensaver-command: window 0x00c00001 mapped.
xscreensaver-command: suspending.
```
with blank/lock
```
xscreensaver: 09:38:16: starting de-race timer (10 seconds.)
xscreensaver: 09:38:16: awaiting idleness.
xscreensaver-command: no response to command.
xscreensaver-systemd: xscreensaver-command failed with 255
xscreensaver: 09:38:27: ClientMessage DEACTIVATE received while inactive: resetting idle timer.
xscreensaver-command: not active: idle timer reset.

xscreensaver: 09:38:30: de-race completed.
xscreensaver: 09:45:40: SUSPEND ClientMessage received.
xscreensaver: 09:45:40: locking.
xscreensaver: 09:45:40: 0: locked mode switching.
xscreensaver: 09:45:40: DPMSForceLevel(dpy, DPMSModeOff) did not change monitor power state.
xscreensaver: 09:45:40: user is idle (ClientMessage)
xscreensaver: 09:45:40: blanking screen at Sat May 30 09:45:40 2020.
xscreensaver: 09:45:40: 0: grabbing keyboard on 0x1be... GrabSuccess.
xscreensaver: 09:45:40: 0: grabbing mouse on 0x1be... GrabSuccess.
xscreensaver: 09:45:40: not launching hack (throttled.)
xscreensaver: 09:45:40: LOCK ClientMessage received while already locked.
xscreensaver-command: window 0x00c00001 mapped.
xscreensaver-command: suspending.

xscreensaver: 09:45:55: unthrottled.
xscreensaver: 09:45:55: DEACTIVATE ClientMessage received.
xscreensaver: 09:45:55: user is active (ClientMessage)
xscreensaver: 09:45:55: pam_start ("xscreensaver", "krm", ...) ==> 0 (Success)
xscreensaver: 09:45:55:   pam_set_item (p, PAM_TTY, ":0.0") ==> 0 (Success)
xscreensaver: 09:45:55:   pam_authenticate (...) ...
xscreensaver-command: deactivating.

xscreensaver: 09:45:55:     pam_conversation (ECHO_OFF="Password: ") ...
xscreensaver: 09:45:55: 0: mouse is at 1046,247.
xscreensaver: 09:45:55: 0: creating password dialog ("")
xscreensaver: 09:45:55: grabbing server...
```
Dialog "Failed to run..." shows in both cases.

**Comment by tsujan** [comment]
> It looks like regardless of the xscreensaver enabled or not, it is the lxqt-powermanagement that is causing this message.

If so, it's annoying and should be fixed.

I'll install and test xscreensaver when I find the time. If I encounter the problem, I'll open a separate issue for it and add its link here.

**Comment by tsujan** [comment]
@kmiernik
I installed xscreensaver and saw the problem first hand. See https://github.com/lxqt/liblxqt/issues/257

Thanks for reporting the second problem!
